### ISSUE TITLE
maxi

### ISSUE THREAD

**Issue by GuidoDipietro** [crisszkutnik/dotfiles#1]
> Here you will find all my dotfiles (configuration files, scripts, etc.). Files and scripts placed on the **Windows** folder are, well, for a windows setup. Everything else is for Linux.

Where's the **Windows** folder then, huh!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!1

**Comment by crisszkutnik** [comment]
Bro I literally created the repo today

**Comment by GuidoDipietro** [comment]
sorry not sorry
